#!/usr/bin/env node
/**
 * Builds src/lib/bible/lsg1910/<BOOK>.json from the public-domain Louis Segond 1910 text
 * in the christos-c/bible-corpus project (CES XML, one <seg> per verse).
 *
 *   node scripts/import-lsg1910.mjs [path/to/French.xml]
 *
 * Without a path the XML is downloaded from GitHub. Output: one file per book,
 * { id, chapters: string[][] } where chapters[c-1][v-1] is verse v of chapter c
 * ("" for the rare verse a corpus leaves out). Typographic apostrophes replace the
 * corpus' backticks; whitespace is collapsed.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const SOURCE_URL = "https://raw.githubusercontent.com/christos-c/bible-corpus/master/bibles/French.xml";
const OUT_DIR = path.join(process.cwd(), "src/lib/bible/lsg1910");

/** Corpus book id → USFM/OSIS-style id used by the app (see src/lib/bible/books.ts). */
const BOOK_IDS = {
  GEN: "GEN", EXO: "EXO", LEV: "LEV", NUM: "NUM", DEU: "DEU", JOS: "JOS", JDG: "JDG", RUT: "RUT",
  "1SA": "1SA", "2SA": "2SA", "1KI": "1KI", "2KI": "2KI", "1CH": "1CH", "2CH": "2CH", EZR: "EZR",
  NEH: "NEH", EST: "EST", JOB: "JOB", PSA: "PSA", PRO: "PRO", ECC: "ECC", SON: "SNG", ISA: "ISA",
  JER: "JER", LAM: "LAM", EZE: "EZK", DAN: "DAN", HOS: "HOS", JOE: "JOL", AMO: "AMO", OBA: "OBA",
  JON: "JON", MIC: "MIC", NAH: "NAM", HAB: "HAB", ZEP: "ZEP", HAG: "HAG", ZEC: "ZEC", MAL: "MAL",
  MAT: "MAT", MAR: "MRK", LUK: "LUK", JOH: "JHN", ACT: "ACT", ROM: "ROM", "1CO": "1CO", "2CO": "2CO",
  GAL: "GAL", EPH: "EPH", PHI: "PHP", COL: "COL", "1TH": "1TH", "2TH": "2TH", "1TI": "1TI", "2TI": "2TI",
  TIT: "TIT", PHM: "PHM", HEB: "HEB", JAM: "JAS", "1PE": "1PE", "2PE": "2PE", "1JO": "1JN", "2JO": "2JN",
  "3JO": "3JN", JUD: "JUD", REV: "REV",
};

function cleanVerse(raw) {
  return raw
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/`/g, "’")
    .replace(/\s+/g, " ")
    .trim();
}

async function main() {
  const xml = process.argv[2]
    ? await readFile(process.argv[2], "utf8")
    : await (await fetch(SOURCE_URL)).text();

  const books = new Map(); // id -> chapters (array of arrays)
  const segRe = /<seg id="b\.([0-9A-Z]+)\.(\d+)\.(\d+)" type="verse">([\s\S]*?)<\/seg>/g;
  let m;
  let verses = 0;
  let gaps = 0;
  while ((m = segRe.exec(xml)) !== null) {
    const [, corpusId, ch, v, body] = m;
    const id = BOOK_IDS[corpusId];
    if (!id) throw new Error(`Unknown corpus book id ${corpusId}`);
    if (!books.has(id)) books.set(id, []);
    const chapters = books.get(id);
    const c = Number(ch) - 1;
    const i = Number(v) - 1;
    while (chapters.length <= c) chapters.push([]);
    while (chapters[c].length < i) {
      chapters[c].push("");
      gaps++;
    }
    chapters[c][i] = cleanVerse(body);
    verses++;
  }

  await mkdir(OUT_DIR, { recursive: true });
  const summary = [];
  for (const [id, chapters] of books) {
    await writeFile(path.join(OUT_DIR, `${id}.json`), JSON.stringify({ id, chapters }) + "\n");
    summary.push(`${id}:${chapters.length}`);
  }
  // Explicit loader map: every bundler can code-split a static import() per book.
  const loaders = [...books.keys()]
    .map((id) => `  ${JSON.stringify(id)}: () => import("./${id}.json"),`)
    .join("\n");
  await writeFile(
    path.join(OUT_DIR, "index.ts"),
    [
      "// Generated by scripts/import-lsg1910.mjs — do not edit by hand.",
      'import type { BibleBookId } from "../books";',
      "",
      "export interface BookData {",
      "  /** USFM book id — typed loosely because it comes straight from JSON. */",
      "  id: string;",
      '  /** chapters[c-1][v-1] is verse v of chapter c; "" marks a verse the source omits. */',
      "  chapters: string[][];",
      "}",
      "",
      "export const LSG1910_BOOKS: Record<BibleBookId, () => Promise<{ default: BookData }>> = {",
      loaders,
      "};",
      "",
    ].join("\n"),
  );
  console.log(`${books.size} books, ${verses} verses, ${gaps} gap(s)`);
  console.log(summary.join(" "));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
